#!/bin/sh

set -eux

dotfiles_dir="$(cd "$( dirname "$0" )" && pwd)"

link() {
  mkdir -p $(dirname "$2")
  ln -sf "$dotfiles_dir/$1" "$2"
}

mkdir -p ~/bin
mkdir -p ~/.config

link bin/kexec ~/bin/kexec
link bin/git-sweep ~/bin/git-sweep
link bin/git-m ~/bin/git-m
link bin/git-tree ~/bin/git-tree

link etc/.gitconfig ~/.gitconfig
link etc/.gitignore ~/.gitignore
link etc/.irbrc ~/.irbrc
link etc/.screenrc ~/.screenrc
link etc/.tigrc ~/.tigrc
link etc/.vimrc ~/.vimrc
link etc/.zshrc ~/.zshrc

link config/ghostty/config "$HOME/Library/Application Support/com.mitchellh.ghostty/config"

case "$(uname)" in
  Darwin)
    if [ -z "$(type brew)" ]; then
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    fi
    brew install \
      awscli \
      colordiff \
      gh \
      ghq \
      git \
      go \
      graphviz \
      grep \
      jq \
      kubectl \
      libyaml \
      nkf \
      openjdk \
      openssl@1.1 \
      peco \
      readline \
      ripgrep \
      stern \
      tig \
      yq

    ln -sf /opt/homebrew/share/git-core/contrib/diff-highlight/diff-highlight ~/bin/diff-highlight
    sudo ln -sfn /opt/homebrew/opt/openjdk/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk.jdk
    ;;
  Linux)
    if [ -f  /usr/share/doc/git/contrib/diff-highlight/diff-highlight ]; then
      sudo ln -sf /usr/share/doc/git/contrib/diff-highlight/diff-highlight /usr/local/bin/diff-highlight
    elif [ -d  /usr/share/doc/git/contrib/diff-highlight ]; then
      cd /usr/share/doc/git/contrib/diff-highlight
      sudo make
      sudo ln -sf /usr/share/doc/git/contrib/diff-highlight/diff-highlight /usr/local/bin/diff-highlight
    fi

    sudo apt install -y zsh
    sudo apt install -y less
    sudo apt install -y peco
    sudo apt install -y nkf
    sudo apt install -y tig
    sudo apt install -y ripgrep
    sudo apt install -y vim
    sudo apt install -y locales-all
    sudo apt install -y jq

    ;;
  *)
    echo "unsupported platform: $(uname)"
    ;;
esac

bash installers/git-wt.sh

if [ ! -d ~/.rbenv ]; then
  git clone https://github.com/rbenv/rbenv.git ~/.rbenv
fi

if [ ! -d ~/.rbenv/plugins/ruby-build ]; then
  mkdir -p ~/.rbenv/plugins
  git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
fi
